name: chrome_apis
version: 0.1.0
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome.dart
environment:
  sdk: '^3.0.0'

dev_dependencies:
  collection:
  puppeteer:
  test:
  web: 0.1.4-beta