name: chrome_apis
version: 0.1.0
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome.dart
environment:
  sdk: '>=3.1.0-310.0.dev'

dev_dependencies:
  build_runner:
  checks:
  collection:
  fetch_client:
  http:
  json_annotation:
  json_serializable:
  puppeteer:
  shelf:
  shelf_router:
  test:
  web: 0.1.4-beta