name: chrome_extension
version: 0.1.0
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome.dart
environment:
  sdk: '^3.0.0'

