import 'package:checks/checks.dart';
import 'package:test/test.dart';

import 'client_side_wrapper.dart';
import 'package:chrome_apis/chrome.dart';

void main() => setup(_tests);

void _tests() {
  test('available', () async {
    check(chrome.action.isAvailable).isFalse();
    check(chrome.alarms.isAvailable).isFalse();
    check(chrome.audio.isAvailable).isFalse();
    check(chrome.bookmarks.isAvailable).isFalse();
    check(chrome.browsingData.isAvailable).isFalse();
    check(chrome.certificateProvider.isAvailable).isFalse();
    check(chrome.commands.isAvailable).isFalse();
    check(chrome.contentSettings.isAvailable).isFalse();
    check(chrome.contextMenus.isAvailable).isFalse();
    check(chrome.cookies.isAvailable).isFalse();
    check(chrome.debugger.isAvailable).isFalse();
    check(chrome.declarativeContent.isAvailable).isFalse();
    check(chrome.declarativeNetRequest.isAvailable).isFalse();
    check(chrome.desktopCapture.isAvailable).isFalse();
    check(chrome.devtools.inspectedWindow.isAvailable).isFalse();
    check(chrome.devtools.network.isAvailable).isFalse();
    check(chrome.devtools.panels.isAvailable).isFalse();
    check(chrome.devtools.recorder.isAvailable).isFalse();
    check(chrome.documentScan.isAvailable).isFalse();
    check(chrome.dom.isAvailable).isFalse();
    check(chrome.downloads.isAvailable).isFalse();
    check(chrome.enterprise.deviceAttributes.isAvailable).isFalse();
    check(chrome.enterprise.hardwarePlatform.isAvailable).isFalse();
    check(chrome.enterprise.networkingAttributes.isAvailable).isFalse();
    check(chrome.enterprise.platformKeys.isAvailable).isFalse();
    check(chrome.extension.isAvailable).isFalse();
    check(chrome.extensionTypes.isAvailable).isFalse();
    check(chrome.fileBrowserHandler.isAvailable).isFalse();
    check(chrome.fileSystemProvider.isAvailable).isFalse();
    check(chrome.fontSettings.isAvailable).isFalse();
    check(chrome.gcm.isAvailable).isFalse();
    check(chrome.history.isAvailable).isFalse();
    check(chrome.i18n.isAvailable).isFalse();
    check(chrome.identity.isAvailable).isFalse();
    check(chrome.idle.isAvailable).isFalse();
    check(chrome.input.ime.isAvailable).isTrue();
    check(chrome.instanceId.isAvailable).isFalse();
    check(chrome.loginState.isAvailable).isFalse();
    check(chrome.management.isAvailable).isFalse();
    check(chrome.notifications.isAvailable).isFalse();
    check(chrome.offscreen.isAvailable).isFalse();
    check(chrome.omnibox.isAvailable).isFalse();
    check(chrome.pageAction.isAvailable).isFalse();
    check(chrome.pageCapture.isAvailable).isFalse();
    check(chrome.management.isAvailable).isFalse();
    check(chrome.permissions.isAvailable).isFalse();
    check(chrome.platformKeys.isAvailable).isFalse();
    check(chrome.power.isAvailable).isFalse();
    check(chrome.printerProvider.isAvailable).isFalse();
    check(chrome.printing.isAvailable).isFalse();
    check(chrome.printingMetrics.isAvailable).isFalse();
    check(chrome.privacy.isAvailable).isFalse();
    check(chrome.processes.isAvailable).isFalse();
    check(chrome.proxy.isAvailable).isFalse();
    check(chrome.runtime.isAvailable).isTrue();
    check(chrome.scripting.isAvailable).isFalse();
    check(chrome.search.isAvailable).isFalse();
    check(chrome.sessions.isAvailable).isFalse();
    check(chrome.sidePanel.isAvailable).isFalse();
    check(chrome.storage.isAvailable).isFalse();
    check(chrome.system.cpu.isAvailable).isFalse();
    check(chrome.system.display.isAvailable).isFalse();
    check(chrome.system.memory.isAvailable).isFalse();
    check(chrome.system.network.isAvailable).isFalse();
    check(chrome.system.storage.isAvailable).isFalse();
    check(chrome.tabCapture.isAvailable).isFalse();
    check(chrome.tabGroups.isAvailable).isFalse();
    check(chrome.tabs.isAvailable).isFalse();
    check(chrome.tts.isAvailable).isFalse();
    check(chrome.ttsEngine.isAvailable).isFalse();
    check(chrome.vpnProvider.isAvailable).isFalse();
    check(chrome.wallpaper.isAvailable).isFalse();
    check(chrome.webAuthenticationProxy.isAvailable).isFalse();
    check(chrome.webNavigation.isAvailable).isFalse();
    check(chrome.webRequest.isAvailable).isFalse();
    check(chrome.windows.isAvailable).isFalse();
    await check(chrome.system.storage.getInfo()).throws<Exception>();
  });
}
