name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - uses: actions/checkout@v2
      - run: dart --version
      - run: |
          (cd chrome_apis && dart pub get) && \
          (cd generator && dart pub get) && \
          (cd examples/extension_dart && dart pub get) && \
          (cd examples/extension_flutter && flutter pub get)
      - run: dart pub get
        working-directory: generator
      - run: flutter analyze --fatal-infos .
      - name: dart test chrome_apis
        run: dart test
        working-directory: chrome_apis
      - name: dart test generator
        run: dart test
        working-directory: generator
      - run: dart tool/gen_apis.dart
        working-directory: generator
      - run: dart tool/prepare_submit.dart
        working-directory: generator
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
